FROM ubuntu
MAINTAINER Torrie Fischer <torrie@cbc.com>

RUN apt-get update -qq &&\
    apt-get install -qq software-properties-common &&\
    apt-add-repository -y ppa:ubuntu-toolchain-r/test &&\
    apt-add-repository -y ppa:afrank/boost &&\
    apt-get update -qq

RUN apt-get purge -qq libboost1.48-dev &&\
    apt-get install -qq libprotobuf8 libboost1.57-all-dev

RUN mkdir -p /srv/cbcd/data

VOLUME /srv/cbcd/data/

ENTRYPOINT ["/srv/cbcd/bin/cbcd"]
CMD ["--conf", "/srv/cbcd/data/cbcd.cfg"]
EXPOSE 51235/udp
EXPOSE 5005/tcp

ADD ./cbcd.cfg /srv/cbcd/data/cbcd.cfg
ADD ./cbcd /srv/cbcd/bin/
